### PR TITLE
OpenSSL package 1.1.0f

### PR DESCRIPTION
**Pull request by MSP-Greg**
I removed the install_docs options.

As before, I don't believe I've checked the i686 package for quite a while...

### CODE REVIEW

**Comment by MSP-Greg** [comment]
You might have a look at the logs, there are some warnings.  It passed all its tests, using it with 2.3, 2.4 and trunk, all Ruby OpenSSL tests pass, and EventMachine builds with it and passes all tests...

**Comment by larskanis** [comment]
Thank you for this PR! I ported the path relocation path from OpenSSL-1.0.2, because it's important for RubyInstaller2. This is why I also added a bunch of new tests to RI2 yesterday.

I'll add proper version constraints to the ruby packages, so that RI2.4 stays on OpenSSL-1.0.2 and RI2.5 is built with OpenSSL-1.1.0.

**Comment by MSP-Greg** [comment]
You're welcome.  Been checking into seeing if RubyGems might update some things and support Windows a little more.

1. I ran this package this morning (breakfast), and I think there were two failures.  I'll run again tonite or tomorrow am.  I didn't have the 'LICENSE' install/package error.

2. I saw the added tests.  Ran them on `rubyinstaller-2.4.1-2-x64_08_07` (I append MM_DD), had the following:
```
61 runs, 62 assertions, 4 failures, 2 errors, 11 skips
```
Same tests, my trunk build from this morning:
```
61 runs, 62 assertions, 5 failures, 2 errors, 11 skips
```

Haven't had a chance to look at it yet.

Thanks again...

**Comment by MSP-Greg** [comment]
For quite a while, I've always had several ruby versions, including several embedded ones.  So, I've always had ENV variables setting SSL files/locations.  Finally decided to remove them and check everything.

Thanks for your work with the path relocation patch.  Without that...

Anyway, updated my appveyor ruby script for more ssl info, ran it on several versions/builds, and I noticed that RI2 OpenSSL::Config::DEFAULT_CONFIG_FILE points a file that doesn't exist.  Doubt it will break anything...

**Comment by larskanis** [comment]
`OpenSSL::Config::DEFAULT_CONFIG_FILE` points to `C:/Ruby24/ssl/openssl.cnf` for instance. This is OK. It's possible to create and use a config for the ruby installation, but currently I don't see a reason, to pre-define such a config. As far as I remember, it is mostly for configuration of OpenSSL engines and CA management.

**Pull request merged**
