### PR TITLE
Add ruby-libyaml

### PR DESCRIPTION
**Pull request by MSP-Greg**

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@larskanis 

Thought I'd try libyaml, as it's the fastest to build.

**Comment by larskanis** [comment]
Thank you - I appreciate your contribution!  It looks very similar to AlexPux receipt but uses `CARCH` instead of `MINGW_CHOST`. What is the reason for this change?

The upload-failure is something that isn't working correctly in the build scripts. It shouldn't try to upload any packages for pull requests. There is no access to secret values (PGP signature key, bintray credentials) in pull requests, so that it wouldn't work.

Since your build script is mostly an tar file version update, wouldn't it make sense to open a pull request on AlexPux repository? It's recommended to increment `pkgrel` by one for such an update (as you've already done). He usually merges and rebuilds such updates within some days.

**Comment by MSP-Greg** [comment]
> Thank you - I appreciate your contribution! It looks very similar to AlexPux receipt but uses CARCH instead of MINGW_CHOST. What is the reason for this change?

As mentioned elsewhere, my initial setup of the code for this goes back quite a while.  I recall that some packages used CARCH, some used MINGW_CHOST.  At the time, I thought that newer, more popular packages used CARCH, so I changed it.

> Since your build script is mostly an tar file version update, wouldn't it make sense to open a pull request on AlexPux repository?

I don't know if there is particular app that MSYS/MinGW is most commonly used with.  LibYaml 0.1.7 was released 2016-08-27.  I (possibly incorrectly) assumed that there was a reason that the package wasn't upgraded.

Likewise for OpenSSL, which hasn't been revised to 1.1.0 (1.1.0a was released 2016-09-22).

Hence, I decided to update the packages, try them with ruby, and if they worked, use them.  Re OpenSSL 1.1.0f, I've also build EventMachine with it.

Would you like these packages, or would you prefer that I go elsewhere?

**Comment by MSP-Greg** [comment]
### Package Thoughts

Back when I first started working with Ruby building, I was experimenting with a derivative of one of the RI branches that was a start towards using MSYS2/MinGW packages and build tools.  Some packages from the repo were used, some were 'hand crafted'.  An example for such might be GDBM or OpenSSL.

At that point, I determined that the possibility existed that new standard packages might cause issues with ruby builds, and hence, the idea of having at least a few ruby specific packages.  Whether that is correct or still holds true, I don't know.  Regardless, I've been building several versions with the packages I have, and tests are consistent.

**Comment by larskanis** [comment]
I think it makes sense to use custom packages for gdbm and OpenSSL.

Until now I ignored gdbm, because it's almost never used. SDM in the stdlibs does the same job and sqlite is better suited for more complex requirements.

OpenSSL-1.1.0 improves both API and ABI in several was, but also brings a bunch of incompatibilities. I did this update for a closed source project lately and I had to solve a huge dependency chain to get it running. There are still projects that aren't compatible with 1.1.0. That's probably the reason it's not yet in MSYS2.

Since OpenSSL-1.1.0 breaks even the ruby API, it's probably best to make the switch with RubyInstaller-2.5 and leave 2.4 on the OpenSSL-1.0.2 branch.

**Comment by MSP-Greg** [comment]
>Until now I ignored gdbm

For me, OpenSSL was the more involved package, GDBM was kind of a 'I suppose this should work, but I don't use it' thing.  It builds a lot faster than OpenSSL...

> Since OpenSSL-1.1.0 breaks even the ruby API

Not sure how, since Ruby OpenSSL somewhat isolates it.  Also, the current [OpenSSL gem](https://rubygems.org/gems/openssl) is compatible  with both 1.1.0 and Ruby >= 2.3.0.  Are you referring to supported protocols/ciphers?

Re 1.1.0, along with tests, I believe both of us have checked for gem compatibility.  At present, nio4r works with it, and EventMachine compiles with it (not a c type, but I think EM can natively call into OpenSSL functions, bypassing Ruby OpenSSL).   My 2.4.1 and ruby_2_4 builds have used 1.1.0f.

My interest in using 1.1.0 is loosely based on two thoughts.  First, it's my impression that 1.1.0 is much more IPv6 aware.  Second, I believe SSL2 and SSL3 are disabled by default.  I have done PR's replacing SSLv3 calls (with SSLv23 or TLS something)...

I rebuilt all three packages using gcc 7.1.0.  Over the next few days, I'll build and save 2.3.4, ruby_2_3, 2.4.1, and ruby_2_4 with the equivalent of the OpenSSL 2.0.4 gem pushed into the build (kind of like `gem update openssl` before the build).  Then, I'll install and test nio4r and EM in all four.  Any other gems I should check?

If all's ok, then I'll PR ruby-openssl & ruby-gdbm to the repo?

One last thing, re libyaml.  My next build, I'm going to remove the package.  I'm guessing Ruby will build without it.  If so, 2.4.1 will be using 0.1.7, and no need for a libyaml package unless some popular extension gems use it.  As it's so simple (and non Ruby specific), I'll PR it to Alexpux/MINGW-packages/mingw-w64-libyaml/.

**Comment by larskanis** [comment]
> > > Since OpenSSL-1.1.0 breaks even the ruby API

> > Not sure how, since Ruby OpenSSL somewhat isolates it. Also, the
> > current OpenSSL
> > gem <https://rubygems.org/gems/openssl> is compatible with both 1.1.0 and
> > Ruby >= 2.3.0. Are you referring to supported protocols/ciphers?


See https://bugs.ruby-lang.org/issues/12324 for breaking changes. Ruby-2.4's OpenSSL deprecates some functions, when compiled with OpenSSL <1.1.0 which are unavailable starting with 1.1.0. So we have ri-2.4 as a transition version, when we switch to OpenSSL-1.1.0 in ri-2.5.

> > Any other gems I should check?
> > If all's ok, then I'll PR ruby-openssl & ruby-gdbm to the repo?
> > I'll PR it to Alexpux/MINGW-packages/mingw-w64-libyaml/.

That all sounds good!

**Comment by MSP-Greg** [comment]
@larskanis

Sorry about delay, spent a little time looking at bundler, which sooner or later will be a default gem.  Quite a mess re MinGW testing (takes longer than trunk `test-all`).  Also, I've got to go thru my old logs, as after running 2.4, etc, there are some failures that I pointed out that were fixed in trunk that probably should be backported...

But, I did check libyaml.  I removed from the MSYS2/MinGW system, and trunk built fine.  As I think I've mentioned, 2.3.4 has 0.1.6, ruby_2_3, 2.4.1, & ruby_2_4 have 0.1.7.  Hence, I don't think the package is  needed for building ruby > 2.3.   You might try removing it, or not installing it...

**Comment by MSP-Greg** [comment]
@larskanis 

Closing this, as libyaml isn't required.  I  renamed, rebuild and tested both gdbm and openssl with 2.3 stable, 2.4 stable and trunk.  I'll post PR's today or tomorrow.  Thanks again.

**Comment by larskanis** [comment]
Great! Looking forward to hear from you.

**Pull request closed without merging**
